name: 'Restricted HTML'
description: 'Provides "Restricted HTML" text format.'
type: 'Text format'
install:
  - filter
config:
  # If the restricted_html format already exists, leave it as-is.
  strict: false
  import:
    filter: '*'
  actions:
    user.role.anonymous:
      grantPermission: 'use text format restricted_html'
