# Schema for the configuration files of the Navigation module.

navigation.settings:
  type: config_object
  label: 'Navigation settings'
  constraints:
    FullyValidatable: ~
  mapping:
    logo_provider:
      type: string
      label: 'Select Navigation logo handling'
      constraints:
        Choice:
          - default
          - hide
          - custom
    logo_managed:
      type: integer
      label: 'Custom logo'
      nullable: true
      constraints:
        Range:
          min: 0
    logo_max_filesize:
      type: integer
      label: 'Maximum file sizes (bytes)'
      constraints:
        NotNull: [ ]
        Range:
          min: 0
    logo_height:
      type: integer
      label: 'Logo expected height'
      constraints:
        NotNull: [ ]
        Range:
          min: 0
    logo_width:
      type: integer
      label: 'Logo expected width'
      constraints:
        NotNull: [ ]
        Range:
          min: 0

navigation.block_layout:
  type: config_object
  mapping:
    sections:
      type: sequence
      sequence:
        type: layout_builder.section

block.settings.navigation_menu:*:
  type: block_settings
  label: 'Menu block'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'
