name: 'Front end theme'
description: 'Sets up Olivero as the front-end theme.'
type: 'Themes'
install:
  - olivero
  - block
config:
  import:
    system:
      - system.menu.account
      - system.menu.main
    olivero:
      - block.block.olivero_account_menu
      - block.block.olivero_breadcrumbs
      - block.block.olivero_content
      - block.block.olivero_main_menu
      - block.block.olivero_powered
      - block.block.olivero_primary_admin_actions
      - block.block.olivero_primary_local_tasks
      - block.block.olivero_secondary_local_tasks
      - block.block.olivero_site_branding
      - core.date_format.olivero_medium
  actions:
    # Create these blocks dynamically so as not to conflict with the blocks created
    # by block_theme_initialize() when Olivero is installed.
    block.block.olivero_messages:
      createIfNotExists:
        theme: olivero
        plugin: system_messages_block
        settings:
          id: system_messages_block
          label: 'Status messages'
          label_display: '0'
          provider: system
      setRegion: highlighted
      setStatus: true
      setWeight: -5
    block.block.olivero_page_title:
      createIfNotExists:
        theme: olivero
        plugin: page_title_block
        settings:
          id: page_title_block
          label: 'Page title'
          label_display: '0'
          provider: core
      setRegion: content_above
      setStatus: true
      setWeight: -5
    system.theme:
      simpleConfigUpdate:
        default: olivero
