name: 'Editorial workflow'
description: 'Provides an editorial workflow for moderating content.'
type: 'Workflow'
install:
  - content_moderation
  # The moderated_content view depends on Node.
  - node
  - views
config:
  # If the config we're shipping already exists, we don't really care what
  # it looks like.
  strict: false
  import:
    content_moderation:
      - views.view.moderated_content
